name: Sample SSH server workflow

on:
  workflow_dispatch:
    inputs:
      sshPublicKey:
        description: 'SSH public key'
        required: true
jobs:
  sample:
    name: Sample
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Start SSH server on failurer 
      uses: ./
      with:
        ngrok-authtoken: "2ObNh7znE7PV5YBQEZRf9UVA7Rc_3Kb7opaUKCnv83y9CgQ4R"
        ssh-public-key: "${{ github.event.inputs.sshPublicKey }}"
