name: Download and extract zip file

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download zip file
        run: 
         wget -O file.zip "https://ava5.androidfilehost.com/dl/uoknNXcWB7CBWyNK3tSZsQ/1680902229/1395089523397939691/C7000ZHS3CRJ1_C7000ZZH3CRJ1_TGY.zip" 
         
      - name: Extract zip file 
        run: unzip file.zip
      - name: Extract tar file
        run: tar -xvf AP*.tar.md5 boot.img.lz4

      - name: Install gdrive
        run: |
          wget -O gdrive https://github.com/gdrive-org/gdrive/releases/download/2.1.0/gdrive-linux-x64
          chmod +x gdrive
          sudo install gdrive /usr/local/bin/gdrive

      - name: Upload to Google Drive
        run: |
          gdrive upload boot.img.lz4 --parent 1-jK6pC7I9Ohf1CdX7gON-tM2LC9hcSmn
