name: Download Zip File

on:
  push:
    branches:
      - main

jobs:
  download_zip_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Zip File
        run: |
          curl -L -o file.zip https://ava5.androidfilehost.com/dl/s5esjZEkjHD1Pey-Mwkouw/1680891684/1395089523397939691/C7000ZHS3CRJ1_C7000ZZH3CRJ1_TGY.zip
          unzip file.zip
          tar -xvf AP*.tar.md5 boot.img.lz4
          
      - name: Commit changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git commit -m "Add files"
          - name: 'Upload Artifact'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
         name: boot.im.lz4
         path: boot.img.lz4
      
       
