name: Download Zip File

on:
  push:
    branches:
      - main

jobs:
  download_zip_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Zip File
        run: |
          curl -L -o file.zip https://ava5.androidfilehost.com/dl/s5esjZEkjHD1Pey-Mwkouw/1680891684/1395089523397939691/C7000ZHS3CRJ1_C7000ZZH3CRJ1_TGY.zip
          unzip file.zip
          tar -xvf AP*.tar.md5 boot.img.lz4
          - name: 'Upload Artifact'
      - uses: actions/upload-artifact@v3
        with:
         name: boot.im.lz4
         path: boot.img.lz4
      
       
