name: Download and extract zipddda file

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download zip file
        run: wget https://ava5.androidfilehost.com/dl/s5esjZEkjHD1Pey-Mwkouw/1680891684/1395089523397939691/C7000ZHS3CRJ1_C7000ZZH3CRJ1_TGY.zip

      - name: Extract tar file
        run: tar -xvf AP*.tar.md5

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: boot.img.lz4
          path: AP/boot.img.lz4
