name: Download and extract zip file

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download zip file
        run: wget https://example.com/archive.zip

      - name: Extract tar file
        run: tar -xvf AP.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: boot.img.lz4
          path: AP/boot.img.lz4
